name: pzed_homes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5+1
  mobile_scanner: ^6.0.11
  supabase_flutter: ^2.10.1

  # Safe for web
  http: ^1.6.0
  url_launcher: ^6.3.2
  go_router: ^14.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1

  # Important web upgrade
  fl_chart: ^0.69.2
  
  table_calendar: ^3.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Mobile only, leave as is
  video_player: ^2.9.0
  chewie: ^1.7.4
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Standard Room/
    - assets/images/Classic Room/
    - assets/images/Diplomatic Room/
    - assets/images/Deluxe Room/
    - assets/images/Executive Room/
    - assets/images/Front View/
    - assets/images/VIP Bar/
    - assets/images/Restaurant/
    - assets/images/Reception/
    - assets/images/Passage/
    - assets/images/Outside bar/
    - assets/images/PZED logo.png
