name: pzed_homes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5+1
  mobile_scanner: ^6.0.11
  supabase_flutter: ^2.10.1

  # Safe for web
  http: ^1.6.0
  url_launcher: ^6.3.2
  go_router: ^14.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1

  # Important web upgrade
  fl_chart: ^0.69.2
  
  table_calendar: ^3.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Mobile only, leave as is
  video_player: ^2.9.0
  chewie: ^1.7.4
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Explicitly list all images for Flutter web compatibility
    # Standard Room
    - assets/images/Standard Room/Standard 1.png
    - assets/images/Standard Room/Standard 2.JPG
    - assets/images/Standard Room/Standard 3.jpg
    - assets/images/Standard Room/Standard 4.JPG
    # Classic Room
    - assets/images/Classic Room/Classic 1.JPG
    - assets/images/Classic Room/Classic 2.png
    - assets/images/Classic Room/Classic 3.JPG
    - assets/images/Classic Room/Classic 4.JPG
    - assets/images/Classic Room/Classic 5.jpg
    # Diplomatic Room
    - assets/images/Diplomatic Room/Diplomatic 1.png
    - assets/images/Diplomatic Room/Diplomatic 2.JPG
    - assets/images/Diplomatic Room/Diplomatic 3.jpg
    # Deluxe Room
    - assets/images/Deluxe Room/Deluxe 1.JPG
    - assets/images/Deluxe Room/Deluxe 2.JPG
    - assets/images/Deluxe Room/Deluxe 3.png
    - assets/images/Deluxe Room/Deluxe 4.JPG
    # Executive Room
    - assets/images/Executive Room/Executive 1.png
    - assets/images/Executive Room/Executive 2.png
    - assets/images/Executive Room/Executive 3.jpg
    # Front View
    - assets/images/Front View/Front View 1.JPG
    - assets/images/Front View/Front View 2.JPG
    - assets/images/Front View/Front View 3.jpg
    - assets/images/Front View/Front View 4.jpg
    - assets/images/Front View/Front View 5.JPG
    - assets/images/Front View/Front View 6.jpg
    # VIP Bar
    - assets/images/VIP Bar/VIP Bar 1.JPG
    - assets/images/VIP Bar/VIP Bar 2.JPG
    # Restaurant
    - assets/images/Restaurant/Restaurant 1.jpg
    # Reception
    - assets/images/Reception/Reception 1.JPG
    - assets/images/Reception/Reception 2.png
    - assets/images/Reception/Reception 3.jpg
    - assets/images/Reception/Reception 4.jpg
    # Passage
    - assets/images/Passage/Passage 1.jpg
    # Outside bar
    - assets/images/Outside bar/Outside Bar 1.JPG
    - assets/images/Outside bar/Outside Bar 2.jpg
    - assets/images/Outside bar/Outside Bar 3.JPG
    # Logo
    - assets/images/PZED logo.png
